version: '3'

services:
  starwars:
    image: starwars:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    # Add additional configurations as needed, such as volumes, networks, etc.
